fix: Added a new prop, updated README, storybook, test files and style fixes
KeyValueSoftwareSystems/react-inline-avatars pull request #15
Opened 2023-12-18 08:56 UTC by anjuca154

## Pull Request Checklist

- [x] **Read the contributing guidelines.**
- [ ] **Linked to an issue:** Fixes # (replace with the issue number, if applicable)
- [x] **Branch is up-to-date with the base branch:** `master`
- [x] **Changes pass tests locally:** `npm test` or `yarn test`
- [x] **Documentation has been updated, if necessary**
- [ ] **Code follows the style guide of the project**
      ​

## Description
- Added a new prop defaultAvatarImage
- Fixed few style issues
- Updated the README, storybook, test files

## Screenshots (if applicable)

​

​

## Additional Notes

​

​

## Related Issues or PRs

​

​

## Reviewer Guidelines

​

​

## Testing Instructions

​

​

## Checklist for Reviewers

​

- [ ] Code follows project conventions and style
- [ ] Changes do not introduce new warnings or errors
- [ ] Unit tests cover the changes
- [ ] Documentation is updated
      ​

## By submitting this pull request, I confirm that my contribution is made under the terms of the MIT License.

2023-12-19 08:04 UTC, bilta-keyvalue requested changes

2023-12-19 08:04 UTC, bilta-keyvalue commented on src/lib/inline-images/InlineImages.tsx
> +            avatarUrl={user.avatarUrl || defaultAvatarImage}
Why do we need to pass defaultAvatarImage here? It is already passed as another prop

2023-12-20 10:44 UTC, manacy-keyvalue commented on src/lib/inline-images/InlineImages.tsx
> +              (0.4 - 0.03 * Math.log10(Math.abs(totalUserCount - data?.length)))
Do we need to add a comment to explain what this computation is intending to do ?

2023-12-21 04:37 UTC, manacy-keyvalue approved these changes

2023-12-21 08:13 UTC, bilta-keyvalue approved these changes

2023-12-21 08:14 UTC, merged